spring.application.name=demo

# Practice DB
spring.datasource.practice.jdbc-url=jdbc:mysql://localhost:3306/practice
spring.datasource.practice.username=root
spring.datasource.practice.password=root
spring.datasource.practice.driver-class-name=com.mysql.cj.jdbc.Driver

# Demo DB
spring.datasource.demo.jdbc-url=jdbc:mysql://localhost:3306/Demo
spring.datasource.demo.username=root
spring.datasource.demo.password=root
spring.datasource.demo.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect